Repository dajxyz/pandemia-fi, pull requests merged in 2020-04, with the labels that each got.

#20 Research page
  pandemia-fi/src/App.js
  pandemia-fi/src/components/categorybadge/categorybadge.tsx
  pandemia-fi/src/components/layout/header.tsx
  pandemia-fi/src/pages/julkaisuja/components/Introduction.tsx
  pandemia-fi/src/pages/julkaisuja/components/SearchBox.tsx
  pandemia-fi/src/pages/julkaisuja/index.ts
  pandemia-fi/src/pages/julkaisuja/julkaisuja.css
  pandemia-fi/src/pages/julkaisuja/julkaisuja.tsx
  pandemia-fi/src/pages/julkaisuja/publications.json
Labels: enhancement

#23 Add a Python script for fetching chart data from ECDC
  pandemia-fi/README.md
  pandemia-fi/data/covid19-today-stats.json
  pandemia-fi/data/legacy-apex-charts.js
  pandemia-fi/package.json
  pandemia-fi/tools/generate_charts.py
  pandemia-fi/tools/legacy-apex-charts.js.j2
Labels: enhancement

#24 Improve Python tooling
  .gitignore
  .python-version
  CONTRIBUTING.md
  pandemia-fi/tools/generate_charts.py
  pandemia-fi/tools/requirements.txt
Labels: documentation, enhancement

#25 Tooling improvements
  .gitignore
  .vscode/settings.json
  CONTRIBUTING.md
  pandemia-fi/package.json
  pandemia-fi/yarn.lock
  project-pandemia.code-workspace
Labels: enhancement

#26 Add tests for React components
  pandemia-fi/src/App.test.js
  pandemia-fi/src/__tests__/App.test.js
  pandemia-fi/src/components/layout/__tests__/footer.test.tsx
  pandemia-fi/src/components/layout/__tests__/header.test.tsx
  pandemia-fi/src/components/layout/__tests__/layout.test.tsx
  pandemia-fi/src/components/layout/layout.tsx
  pandemia-fi/src/components/link/__tests__/link.test.tsx
  pandemia-fi/src/components/spinner/__tests__/spinner.test.tsx
  pandemia-fi/src/pages/about/__tests__/About.test.tsx
  pandemia-fi/src/pages/about/__tests__/Person.test.tsx
  pandemia-fi/src/pages/julkaisuja/__tests__/julkaisuja.test.tsx
  pandemia-fi/src/pages/julkaisuja/components/__tests__/Introduction.test.tsx
  pandemia-fi/src/pages/julkaisuja/components/__tests__/SearchBox.test.tsx
  pandemia-fi/src/pages/julkaisuja/julkaisuja.tsx
  pandemia-fi/src/pages/landing/__tests__/Landing.test.tsx
  pandemia-fi/src/pages/landing/components/LinksCard/__tests__/LinksCard.test.tsx
  pandemia-fi/src/pages/landing/components/finland-and-eu-chart/__tests__/finland-and-eu-chart.test.tsx
  pandemia-fi/src/pages/landing/components/hero-chart-card/__tests__/hero-chart-card.test.tsx
  pandemia-fi/src/pages/landing/components/nordics-chart/__tests__/nordics-chart.test.tsx
  pandemia-fi/src/pages/landing/components/number-metric-card/__tests__/number-metric-card.test.tsx
  pandemia-fi/src/pages/tietopankki/__tests__/tietopankki.test.tsx
  pandemia-fi/src/pages/uutishuone/__tests__/uutishuone.test.tsx
  pandemia-fi/src/pages/uutishuone/components/news-feed-item/__tests__/news-feed-item.test.tsx
  pandemia-fi/src/pages/uutishuone/components/sidebar-item/__tests__/sidebar-item.tsx
Labels: bug, enhancement
